logging:
  level:
    ROOT: WARN
    nl.kadaster: DEBUG
    org.dotwebstack: DEBUG
dotwebstack:
  resourcePath: ${resource_path}
  rdf4j:
    shape:
      language: nl
      graph: http://brk.basisregistraties.overheid.nl/brk/shapes
      prefix: http://brk.basisregistraties.overheid.nl/def/brk/

  template:
    baseUrl: ${BASE_URL:https://brk.basisregistraties.overheid.nl}

  plugins:
    marklogic:
      queryOptions: brk
      repositories:
        - name: brk
          host: ${ML_HOST:pdok-kdp-marklogic.in.kadaster.nl}
          port: ${ML_PORT:8011}
          user: ${SECRET_ML_USERNAME:admin}
          password: ${SECRET_ML_PASSWORD:password}
          basePath: ${ML_BASEPATH:/services-brk-ld-pr-280-integratietest/}