language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
env:
  global:
    secure: lSwtd+NM6cRmEAUAP2xxr2MvhvOMwjTw4+2Z2tLxXRauwDURCOzjSprXNeG3r93UkigEdIzG1Chtkmz224ualLS93Vc2bQ8RYLs76yKNmddRife5FzTcX73B3yo9AS8Uju3Jzyw+3o6CYQ61aQPR/zIIr7AU9nyxphO2xSFWMSq5sLG5Lh0gkIEl+2ZdWRe2yItRmWi2+5fDeKJBPvDmmZNKQ7i/EzCAXZBQ8YYSkCiTOjBtsn2HvimHk8amaw6wTB+v2PZM5zo0UlJadMrEdG5+oQFI0t7J/r2eRdu/XHmOM570akNu3nmh0xvZPQ0R+I1ZDFZSmGN/eoe31wMxOtZZPtS5Kc200AcVIPiA2oT3NYh7H0NnST5s0Ow4nXX+EW86NsDfvZ7Vx6mSMoh3pSki3dvVNWjg662214g+egY7MF66w14T0OV5PanFg6JJ23Fmp8Js/UgxnV5J1Yd+wcMh8i8RruSVPTV3Ai/OuM5mfBa6UWjIWoJMV1oZ1QA7lS2LaU/mWFp602dzlpxJhMpZDj/iB5vOWv8hdK0zGmR4qbXUZ7kc1WXabWx1rM5cIQ83TguF2LMtqUF2PR3hcJ0ltu/okEcX2FKCu94CeXsC6swo7RYaUL2hgiAIx9G7uJHCSzR5CeEpzuJPeHIQ7OgnVXYzwFm6JMs6BKhD1vk=
addons:
  sonarcloud:
    organization: dotwebstack
    token:
      secure: HSdBT8AaylyTtZHq73L98HmMXvuUQ7exj4/ApZnu6z1k5q7mymphDjOuMrXkWL4Tp6+2HAXpqlKnckrjx2G7h/3O5N/hf1FQMrnbQK8jGeKtG8X0yuRg/H2CZwv4aVORlrvpt86FnwivuC3TaOhcecbcs5b/f1kORn6aSmyV6KAV1rV6uNzZPHXNdcC+YK98RpTHxzh2kjW9/IHMByn14Jli27/GLW4ks5Uc7oyC1vGSIHuEqAcGPPoXVUxsfOYEakPsdyKHCk71HQ1OdukZahkNnjdSOaJNKjBJFlcgg4umYUuRD4cRVV9rDSOqwuYGwktpU7tLveggM9Ihyv/WEuOmplms8pjZH5aY6FI8/UHh83tybQfSfyE+HAMnJIyVZ6iVLEh2GDGfd45WRmqR25BSsKhU/F45nyahVzEP3jMZQ9fXOg4cYzEbdD8Df3zOjw6Q4vUqno7MbieH3QEDYuX++4GrzILFwSX6j+4zIRGayZyZRrQuQw1GSvf9ro+T2G9B5XS4xJcDFQ2GJ7+CgVHwBjC+e9zGkzv6ipx8oI1BO3vcaX7vWvgtUGhzlvMArPdZAvGfM89XkGKpShMFqZvrJXlCqqHiWF4J4f9Qtly6//Er5Rf3vSC53BJUIvd+R1BeVg3/Ynb/blwLJHRTwiKsqHrwJOGH+DdC3+Scois=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
deploy:
  - provider: script
    script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy
    skip_cleanup: true
    on:
      branch: master
