<?xml version='1.0' encoding='UTF-8'?>
<sparql xmlns='http://www.w3.org/2005/sparql-results#'>
	<head>
		<variable name='brewery'/>
		<variable name='name'/>
		<variable name='founded'/>
	</head>
	<results>
		<result>
			<binding name='brewery'>
				<uri>https://github.com/dotwebstack/beer/id/brewery/4</uri>
			</binding>
			<binding name='name'>
				<literal xml:lang='nl'>Ambrass Bierbrouwerij</literal>
			</binding>
			<binding name='founded'>
				<literal datatype='http://www.w3.org/2001/XMLSchema#date'>2014-01-01</literal>
			</binding>
		</result>
	</results>
</sparql>
