features:
  - paging

spatial:
  sourceCrs: EPSG:4258

rml:
  namespacePrefixes:
    beer: http://dotwebstack.org/def/beer#
    foaf: http://xmlns.com/foaf/0.1/
    gsp: http://www.opengis.net/ont/geosparql#
