logging:
  level:
    root: INFO
    org.dotwebstack: DEBUG

dotwebstack:
  openapi:
    apiDocPublicationPath: /openapi.yaml
    spatial:
      sridParameter:
        name: accept-crs
        valueMap:
          '[epsg:28992]': 28992
  config: dotwebstack.yaml
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: postgres
    schema: dbeerpedia
  base_url: localhost:8080
