openapi: 3.0.2

info:
  title: Ruimtelijke Plannen API
  version: 3.0.0

components:
  schemas:
    Beer:
      type: object
      required:
        - identifier
        - name
        - test
      properties:
        identifier:
          type: string
        name:
          type: string
          nullable: true
        test:
          type: string
    Breweries:
      type: array
      items:
       $ref: '#/components/schemas/Brewery'
    Brewery:
      type: object
      required:
        - identifier
        - name
      properties:
        identifier:
          type: string
        name:
          type: string
          nullable: true
        beers:
          type: array
          items:
            $ref: '#/components/schemas/Beer'

paths:
  /breweries:
    get:
      x-dws-query: default_breweries
      responses:
        200:
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Breweries'