openapi: 3.0.2

info:
  title: Breweries
  version: 3.0.0

components:
  schemas:
    Beer:
      type: object
      required:
        - identifier
        - name
      properties:
        identifier:
          type: string
        name:
          type: string
          nullable: true
    Breweries:
      type: array
      items:
       $ref: '#/components/schemas/Brewery'
    Brewery:
      type: object
      required:
        - identifier
        - name
      properties:
        identifier:
          type: string
        name:
          type: string
          nullable: true
        openinghours:
          type: string
          nullable: true
        beers:
          type: array
          items:
            $ref: '#/components/schemas/Beer'
    SortField:
      type: array
      items:
        type: object
        properties:
          field:
            type: string
          order:
            type: string



paths:
  /breweries:
    get:
      x-dws-query: breweries
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: sinceAfter
          in: header
          required: true
          schema:
            type: string
        - name: sort
          in: header
          x-dws-type: sort
          schema:
            type: array
            default: ['name']
            items:
              type: string
              enum: ['name', '-founded']
      responses:
        200:
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Breweries'
  /brewery/{identifier}:
    get:
      x-dws-query: brewery
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Brewery'