logging:
  level:
    org.dotwebstack: DEBUG

server:
  port: 8081

dotwebstack:
  orchestrate:
    endpoint: ${PROXY_URL:localhost:8080}
    bearerAuth: ${PROXY_BEARER_AUTH:secret}
  template:
    baseUrl: http://localhost:8081
