package org.dotwebstack.framework.frontend.soap.handlers;

public class MockResponse {
  
  public static final String GET_VEHICLE_NAMES = "<?xml version=\"1.0\"?>"
      + "<soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope/\">"
      + "  <soap:Body xmlns:m=\"http://www.example.org/soaptest\">"
      + "    <m:GetTestResult>"
      + "      <m:Value>TEST!</m:Value>"
      + "    </m:GetTestResult>"
      + "  </soap:Body>"
      + "</soap:Envelope>";

  public static final String GET_DOMAIN_TABLE_NAMES = "<?xml version=\"1.0\"?>"
      + "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">"
      + "   <s:Body>"
      + "      <GetDomainTableNamesResponse xmlns=\"http://rws.services.nl/DomainTableWS/2010/10\">"
      + "         <GetDomainTableNamesResult xmlns:a=\"http://rws.services.nl/DomainTableWS"
          + "/Contracts/2010/10\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\">"
      + "            <a:DomainTableNames>"
      + "               <a:string>Aanduiding_naamgebruik</a:string>"
      + "               <a:string>Aanslag_type</a:string>"
      + "               <a:string>Aanvoereenheid_soorten</a:string>"
      + "               <a:string>Aanvoergebied_soorten</a:string>"
      + "               <a:string>Aanwezig_afwezig_onbekend</a:string>"
      + "               <a:string>Academische_titel</a:string>"
      + "               <a:string>Adellijke_titel_of_predikaat</a:string>"
      + "               <a:string>Afleveringspunt_soorten</a:string>"
      + "               <a:string>AfsluitmiddelType</a:string>"
      + "               <a:string>Afvoergebied_soorten</a:string>"
      + "               <a:string>Afwateringseenheid_soorten</a:string>"
      + "               <a:string>AtRisktype</a:string>"
      + "               <a:string>BBP_beheerproduct</a:string>"
      + "               <a:string>BBP_beleidsproduct</a:string>"
      + "               <a:string>Bedrijfstakken_WVOW</a:string>"
      + "               <a:string>Beheersvormen_waterkering</a:string>"
      + "               <a:string>BekledingType</a:string>"
      + "               <a:string>Bekleding_materiaal</a:string>"
      + "               <a:string>BekledinglaagType</a:string>"
      + "               <a:string>Belastingsoorten</a:string>"
      + "               <a:string>Bemalen_of_vrij_verval</a:string>"
      + "               <a:string>Bemonsteringsapparaat</a:string>"
      + "               <a:string>Bemonsteringsmethode</a:string>"
      + "               <a:string>Bemonsteringssoort</a:string>"
      + "               <a:string>Beoordeling_schade</a:string>"
      + "               <a:string>BeschermdGebiedtype</a:string>"
      + "               <a:string>Bestemmingen_afvalwater</a:string>"
      + "               <a:string>Besturingswijze</a:string>"
      + "               <a:string>Bevaarbaarheidsklassen</a:string>"
      + "               <a:string>BevoegdGezagSoort</a:string>"
      + "               <a:string>Beweegbare_bruggen</a:string>"
      + "               <a:string>Biotaxon</a:string>"
      + "               <a:string>Boomhoogte</a:string>"
      + "               <a:string>Brander</a:string>"
      + "            </a:DomainTableNames>"
      + "         </GetDomainTableNamesResult>"
      + "      </GetDomainTableNamesResponse>"
      + "   </s:Body>"
      + "</s:Envelope>";

  public static final String GET_DATE_LAST_PUBLISHED = "<?xml version=\"1.0\"?>"
      + "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">"
      + "   <s:Body>"
      + "      <GetDateLastPublishedResponse xmlns=\"http://rws.services.nl/DomainTableWS/2010/10\">"
      + "         <GetDateLastPublishedResult xmlns:a=\"http://rws.services.nl/DomainTableWS"
          + "/Contracts/2010/10\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\">"
      + "            <a:MostRecentPublicationDate>2011-10-19T00:00:00</a:MostRecentPublicationDate>"
      + "         </GetDateLastPublishedResult>"
      + "      </GetDateLastPublishedResponse>"
      + "   </s:Body>"
      + "</s:Envelope>";

  public static final String GET_DOMAIN_TABLE_CHANGES_INFO = "<?xml version=\"1.0\"?>"
      + "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">"
      + "   <s:Body>"
      + "      <GetDomainTableChangesInfoResponse xmlns=\"http://rws.services.nl/DomainTableWS/2010/10\">"
      + "         <GetDomainTableChangesInfoResult xmlns:a=\"http://rws.services.nl/DomainTableWS"
          + "/Contracts/2010/10\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\">"
      + "            <a:MaxDataRowsInResponse>2500</a:MaxDataRowsInResponse>"
      + "            <a:MetaData>"
      + "               <a:MetaDataColumn>"
      + "                  <a:ColumnNumber>1</a:ColumnNumber>"
      + "                  <a:Datatype>DtInteger</a:Datatype>"
      + "                  <a:Description>ID-kolom</a:Description>"
      + "                  <a:FieldLength>6</a:FieldLength>"
      + "                  <a:Name>ID</a:Name>"
      + "                  <a:NumberOfDecimals>0</a:NumberOfDecimals>"
      + "                  <a:PKSequenceNumber>-1</a:PKSequenceNumber>"
      + "                  <a:Required>true</a:Required>"
      + "                  <a:Unique>true</a:Unique>"
      + "               </a:MetaDataColumn>"
      + "               <a:MetaDataColumn>"
      + "                  <a:ColumnNumber>2</a:ColumnNumber>"
      + "                  <a:Datatype>DtString</a:Datatype>"
      + "                  <a:Description>Omschrijving</a:Description>"
      + "                  <a:FieldLength>60</a:FieldLength>"
      + "                  <a:Name>Omschrijving</a:Name>"
      + "                  <a:NumberOfDecimals>-1</a:NumberOfDecimals>"
      + "                  <a:PKSequenceNumber>1</a:PKSequenceNumber>"
      + "                  <a:Required>true</a:Required>"
      + "                  <a:Unique>true</a:Unique>"
      + "               </a:MetaDataColumn>"
      + "            </a:MetaData>"
      + "            <a:Name>Boomhoogte</a:Name>"
      + "            <a:TotalDataRows>0</a:TotalDataRows>"
      + "         </GetDomainTableChangesInfoResult>"
      + "      </GetDomainTableChangesInfoResponse>"
      + "   </s:Body>"
      + "</s:Envelope>";

  public static final String GET_DOMAIN_TABLE_CHANGES = "<?xml version=\"1.0\"?>"
      + "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">"
      + "   <s:Body>"
      + "      <GetDomainTableChangesResponse xmlns=\"http://rws.services.nl/DomainTableWS/2010/10\">"
      + "         <GetDomainTableChangesResult xmlns:a=\"http://rws.services.nl/DomainTableWS"
          + "/Contracts/2010/10\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\">"
      + "            <a:DataRowsReadPage>0</a:DataRowsReadPage>"
      + "            <a:PageSize>1</a:PageSize>"
      + "            <a:TotalDataRows>0</a:TotalDataRows>"
      + "            <a:Data/>"
      + "            <a:Name>Boomhoogte</a:Name>"
      + "         </GetDomainTableChangesResult>"
      + "      </GetDomainTableChangesResponse>"
      + "   </s:Body>"
      + "</s:Envelope>";

  public static final String GET_DOMAIN_TABLE_INFO = "<?xml version=\"1.0\"?>"
      + "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">"
      + "   <s:Body>"
      + "      <GetDomainTableInfoResponse xmlns=\"http://rws.services.nl/DomainTableWS/2010/10\">"
      + "         <GetDomainTableInfoResult xmlns:a=\"http://rws.services.nl/DomainTableWS"
          + "/Contracts/2010/10\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\">"
      + "            <a:MaxDataRowsInResponse>2500</a:MaxDataRowsInResponse>"
      + "            <a:MetaData>"
      + "               <a:MetaDataColumn>"
      + "                  <a:ColumnNumber>1</a:ColumnNumber>"
      + "                  <a:Datatype>DtInteger</a:Datatype>"
      + "                  <a:Description>ID-kolom</a:Description>"
      + "                  <a:FieldLength>6</a:FieldLength>"
      + "                  <a:Name>ID</a:Name>"
      + "                  <a:NumberOfDecimals>0</a:NumberOfDecimals>"
      + "                  <a:PKSequenceNumber>-1</a:PKSequenceNumber>"
      + "                  <a:Required>true</a:Required>"
      + "                  <a:Unique>true</a:Unique>"
      + "               </a:MetaDataColumn>"
      + "               <a:MetaDataColumn>"
      + "                  <a:ColumnNumber>2</a:ColumnNumber>"
      + "                  <a:Datatype>DtString</a:Datatype>"
      + "                  <a:Description>Omschrijving</a:Description>"
      + "                  <a:FieldLength>60</a:FieldLength>"
      + "                  <a:Name>Omschrijving</a:Name>"
      + "                  <a:NumberOfDecimals>-1</a:NumberOfDecimals>"
      + "                  <a:PKSequenceNumber>1</a:PKSequenceNumber>"
      + "                  <a:Required>true</a:Required>"
      + "                  <a:Unique>true</a:Unique>"
      + "               </a:MetaDataColumn>"
      + "            </a:MetaData>"
      + "            <a:Name>Boomhoogte</a:Name>"
      + "            <a:TotalDataRows>7</a:TotalDataRows>"
      + "         </GetDomainTableInfoResult>"
      + "      </GetDomainTableInfoResponse>"
      + "   </s:Body>"
      + "</s:Envelope>";

  public static final String GET_DOMAIN_TABLE = "<?xml version=\"1.0\"?>"
      + "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">"
      + "   <s:Body>"
      + "      <GetDomainTableResponse xmlns=\"http://rws.services.nl/DomainTableWS/2010/10\">"
      + "         <GetDomainTableResult xmlns:a=\"http://rws.services.nl/DomainTableWS"
          + "/Contracts/2010/10\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\">"
      + "            <a:DataRowsReadPage>1</a:DataRowsReadPage>"
      + "            <a:PageSize>1</a:PageSize>"
      + "            <a:TotalDataRows>7</a:TotalDataRows>"
      + "            <a:Data>"
      + "               <a:DataRow>"
      + "                  <a:BeginDate>2011-10-19T00:00:00</a:BeginDate>"
      + "                  <a:EndDate>2999-12-31T00:00:00</a:EndDate>"
      + "                  <a:Fields>"
      + "                     <a:DataField i:type=\"a:IntegerField\">"
      + "                        <a:IsNull>false</a:IsNull>"
      + "                        <a:Name>ID</a:Name>"
      + "                        <a:Data>2</a:Data>"
      + "                     </a:DataField>"
      + "                     <a:DataField i:type=\"a:StringField\">"
      + "                        <a:IsNull>false</a:IsNull>"
      + "                        <a:Name>Omschrijving</a:Name>"
      + "                        <a:Data>12-15 meter</a:Data>"
      + "                     </a:DataField>"
      + "                  </a:Fields>"
      + "               </a:DataRow>"
      + "            </a:Data>"
      + "            <a:Name>Boomhoogte</a:Name>"
      + "         </GetDomainTableResult>"
      + "      </GetDomainTableResponse>"
      + "   </s:Body>"
      + "</s:Envelope>";

}