PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dws:     <https://github.com/dotwebstack/beer/def#>

SELECT ?brewery ?name ?founded
  WHERE {
    ?brewery rdf:type dws:Brewery .
    OPTIONAL {
      ?brewery dws:localName ?name .
      FILTER ( LANG( ?name ) = "nl" )
    }
    OPTIONAL {
      ?brewery dws:founded ?founded .
    }
    FILTER ( ?brewery = ?subject)
}
