logging:
  level:
    root: INFO
    org.dotwebstack: DEBUG

server:
  port: 8081

dotwebstack:
  graphql:
    proxies:
      localhostProxy:
        uri: ${PROXY_URL:localhost:8080}
        bearerAuth: ${PROXY_BEARER_AUTH:secret}
