queries:
  beer:
    type: Beer
    keys:
      - field: identifier
  beerCollection:
    type: Beer
    list: true
  brewery:
    type: Brewery
    keys:
      - field: identifier
  breweryCollection:
    type: Brewery
    list: true

objectTypes:
  Beer:
    backend: rdf4j
    nodeShape: https://github.com/dotwebstack/beer/shapes#Beer
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      abv:
        type: Float
      brewery:
        type: Brewery
        joinProperties:
          - name: brewery
            referencedField: identifier

  Brewery:
    backend: rdf4j
    nodeShape: https://github.com/dotwebstack/beer/shapes#Brewery
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      beers:
        type: Beer
        list: true
        nullable: true
        mappedBy: brewery
      geometry:
        type: Geometry
        nullable: true
        arguments:
          - name: type
            type: GeometryType
            nullable: true
      postalAddress:
        type: Address
        nullable: true
        joinProperties:
          - name: postal_address
            referencedField: identifier
      visitAddress:
        type: Address
        nullable: true
        joinProperties:
          - name: visit_address
            referencedField: identifier

  Address:
    backend: rdf4j
    nodeShape: https://github.com/dotwebstack/beer/shapes#Address
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
        nullable: true
      street:
        type: String
      city:
        type: String
