queries:
  beer:
    type: Beer
    keys:
      - field: identifier
  beerCollection:
    type: Beer
    list: true
  brewery:
    type: Brewery
    keys:
      - field: identifier
  breweryCollection:
    type: Brewery
    list: true

objectTypes:
  Beer:
    keys:
      - field: identifier
    sortableBy:
      name:
        - field: name
          direction: ASC
        - field: abv
          direction: DESC
      abv:
        - field: abv
          direction: ASC
    fields:
      identifier:
        type: ID
      name:
        type: String
      abv:
        type: Float
      brewery:
        type: Brewery

  Brewery:
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      beers:
        type: Beer
        list: true
        nullable: true
        mappedBy: brewery
      geometry:
        type: Geometry
        nullable: true
      postalAddress:
        type: Address
        nullable: true
      visitAddress:
        type: Address
        nullable: true

  Address:
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
        nullable: true
      street:
        type: String
      city:
        type: String
