queries:
  beer:
    type: Beer
    keys:
      - identifier
  beerByUri:
    type: Beer
    keys:
      - uri
  beerCollection:
    type: Beer
    list: true
  brewery:
    type: Brewery
    keys:
      - identifier
  breweryCollection:
    type: Brewery
    list: true

objectTypes:
  Beer:
    keys:
      - identifier
    sortableBy:
      name:
        - field: brewery.name
          direction: ASC
        - field: name
          direction: DESC
    fields:
      uri:
        type: String
        resource: true
      identifier:
        type: String
      name:
        type: String
      abv:
        type: Float
        nullable: true
      brewery:
        type: Brewery

  Brewery:
    keys:
      - identifier
    fields:
      uri:
        type: String
        resource: true
      identifier:
        type: String
      name:
        type: String
      beers:
        type: Beer
        list: true
        nullable: true
        mappedBy: brewery
      geometry:
        type: Geometry
        nullable: true
      postalAddress:
        type: Address
        nullable: true
      visitAddress:
        type: Address
        nullable: true

  Address:
    keys:
      - identifier
    fields:
      identifier:
        type: ID
        nullable: true
      street:
        type: String
      city:
        type: String
