PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
construct {
  ?subject ?p ?o .
  ?o ?p1 ?o2 .
  ?i_s ?i_p ?subject .
}
FROM <http://brk.basisregistraties.overheid.nl/id/begrippenkader/brk>
FROM <http://brk.basisregistraties.overheid.nl/def/brk>
{
  ?subject ?p ?o .
  optional {
    ?o ?p1 ?o2 .
    filter (!strstarts(str(?o), "http"))
  }
  optional {
  	?i_s ?i_p ?subject .
  }
}