logging:
  level:
    root: INFO
    org.dotwebstack: DEBUG

server:
  port: 8081

dotwebstack:
  orchestrate:
    root: dbeerpedia
    subschemas:
      dbeerpedia:
        endpoint: ${PROXY_URL:localhost:8080}
