logging:
  level:
    root: INFO
    org.dotwebstack: DEBUG

dotwebstack:
  config: /home/hupa/projects/dhub-tenants/brk/brk-v1/generated/lookup.yaml
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: brk-v1

