version: '3.9'

services:
  postgres:
    image: postgis/postgis:11-3.1
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
