spatial:
  srid:
    28992:
      dimensions: 2
      scale: 4
      bboxColumnSuffix: _bbox
    7415:
      dimensions: 3
      scale: 4
      bboxColumnSuffix: _bbox
      equivalent: 28992
    9067:
      dimensions: 2
      scale: 9
      columnSuffix: _etrs89
    7931:
      dimensions: 3
      scale: 9
      columnSuffix: _etrs89
      equivalent: 9067

contexts:
  history:
    fields:
      validOn:
        type: Date
        default: NOW
      availableOn:
        type: DateTime
        default: NOW

queries:
  beer:
    type: Beer
    keys:
      - identifier
  beerCollection:
    type: Beer
    list: true
    pageable: true
  brewery:
    type: Brewery
    keys:
      - identifier
  breweryCollection:
    type: Brewery
    list: true
    pageable: true
  breweryCollectionInContext:
    type: Brewery
    list: true
    pageable: true
    context: history

objectTypes:
  Beer:
    table: dbeerpedia.beers
    filters:
      name:
        field: name
      breweryCity:
        field: brewery.visitAddress.city
      ingredientName:
        field: ingredients.name
      retired: {}
    sortableBy:
      name:
        - field: name
          direction: ASC
      breweryCity:
        - field: brewery.visitAddress.city
          direction: ASC
    fields:
      identifier:
        type: ID
      name:
        type: String
      abv:
        type: Float
      soldPerYear:
        type: Int
      retired:
        type: Boolean
      brewery:
        type: Brewery
        joinColumns:
          - name: brewery
            referencedColumn: record_id
      ingredient:
        type: Ingredient
        nullable: true
        joinTable:
          name: dbeerpedia.beers_ingredients
          joinColumns:
            - name: beers_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: ingredients_identifier
              referencedField: identifier
      ingredients:
        type: Ingredient
        list: true
        joinTable:
          name: dbeerpedia.beers_ingredients
          joinColumns:
            - name: beers_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: ingredients_identifier
              referencedField: identifier
      ingredientAgg:
        aggregationOf: Ingredient
        joinTable:
          name: dbeerpedia.beers_ingredients
          joinColumns:
            - name: beers_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: ingredients_identifier
              referencedField: identifier
      taste:
        type: Taste
        list: true
      validStart:
        type: Date
      validEnd:
        type: Date
        nullable: true

  Brewery:
    table: dbeerpedia.breweries
    sortableBy:
      name:
        - field: name
          direction: ASC
      nameDesc:
        - field: name
          direction: DESC
    filters:
      name: { }
      status: { }
      geometry: { }
      postalStreet:
        field: postalAddress.street
      postalCity:
        field: postalAddress.city
      visitStreet:
        field: visitAddress.street
      visitCity:
        field: visitAddress.city
      historyAge:
        field: history.age
      beerName:
        field: beers.name
      relatedToName:
        field: relatedTo.name
      relatedToStatus:
        field: relatedTo.status
    fields:
      identifier:
        type: String
      name:
        type: String
      status:
        type: String
      geometry:
        type: Geometry
        nullable: true
      postalAddress:
        type: Address
        nullable: true
        joinColumns:
          - name: postal_address
            referencedField: identifier
      visitAddress:
        type: Address
        nullable: true
        joinColumns:
          - name: visit_address
            referencedField: identifier
      beer:
        type: Beer
        nullable: true
        mappedBy: brewery
        keys:
          - identifier
      beers:
        type: Beer
        list: true
        nullable: true
        mappedBy: brewery
#        pageable: true
      beerAgg:
        aggregationOf: Beer
        mappedBy: brewery
      history:
        type: History
      relatedTo:
        type: Brewery
        list: true
        joinTable:
          name: dbeerpedia.breweries__related_to
          joinColumns:
            - name: brewery_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: brewery_related_to_identifier
              referencedField: identifier

  Ingredient:
    table: dbeerpedia.ingredients
    fields:
      identifier:
        type: ID
      name:
        type: String
      weight:
        type: Float

  Address:
    table: dbeerpedia.addresses
    fields:
      identifier:
        type: ID
      street:
        type: String
      city:
        type: String

  History:
    fields:
      age:
        type: Int
        column: his_age
      history:
        type: String
        column: his_history

enumerations:
  Taste:
    values: [MEATY, FRUITY, SMOKY, SPICY, WATERY]
