logging:
  level.org.dotwebstack: DEBUG

dotwebstack:
  rdf4j:
    shape:
      graph: http://dbeerpedia.com/id/shapes
      prefix: http://dbeerpedia.com/def/
    prefixes:
      rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
      dbeer: http://dbeerpedia.com/def#
      brewery_id: http://dbeerpedia.com/id/brewery/
    repositories:
      data:
        type: sparql
        args:
          endpointUrl: https://data.pdok.nl/sparql
