objectTypes:
  Beer:
    backend: json
    path: "$..beer"
    keys:
      - field: identifier
    fields:
      name:
      abv:
      brewery:
#  Brewery:
#    backend: json
#    path: "$..brewery"
#    keys:
#      - field: identifier
#    fields:
#      name:
#      visistAddress:
#      postalAddress:
