queries:
  beers:
    type: Beer
    list: true
  beer:
    type: Beer
    keys:
      - field: identifier
    nullable: true
#  breweries:
#    type: Brewery
#    list: true

objectTypes:
  Beer:
    file: data.json
    queryPaths:
      beer: $.beers[*].beer[?]
      beers: $.beers[*].beer
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      abv:
        type: Float
      brewery:
        type: Brewery

  Brewery:
#    queryPaths:
#      brewery: $..breweries[?]
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      beers:
        type: Beer
        list: true
      visistAddress:
        type: Address
        nullable: true
      postalAddress:
        type: Address
        nullable: true

  Address:
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      street:
        type: String
      city:
        type: String