features:
  - paging

spatial:
  sourceCrs: EPSG:28992

subscriptions:
  beerSubscription:
    type: Beer
  brewerySubscription:
    type: Brewery

contexts:
  history:
    fields:
      validOn:
        type: Date
        default: NOW
      availableOn:
        type: DateTime
        default: NOW

queries:
  beer:
    type: Beer
    context: history
  beerCollection:
    type: Beer
    list: true
    context: history
  brewery:
    type: Brewery
    keys:
      - identifier
    context: history
  breweryCollection:
    type: Brewery
    list: true
    context: history

objectTypes:
  Beer:
    table: dbeerpedia.beers
    filters:
      breweryCity:
        field: brewery.visitAddress.city
    sortableBy:
      name:
        - field: name
          direction: ASC
      breweryCity:
        - field: brewery.visitAddress.city
          direction: ASC
    fields:
      identifier:
        type: ID
      name:
        type: String
      abv:
        type: Float
      soldPerYear:
        type: Int
      retired:
        type: Boolean
      brewery:
        type: Brewery
        joinColumns:
          - name: brewery
            referencedField: record_id
      ingredients:
        type: Ingredient
        list: true
        joinTable:
          name: dbeerpedia.beers_ingredients
          joinColumns:
            - name: beers_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: ingredients_identifier
              referencedField: identifier
      ingredientAgg:
        aggregationOf: Ingredient
        joinTable:
          name: dbeerpedia.beers_ingredients
          joinColumns:
            - name: beers_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: ingredients_identifier
              referencedField: identifier
      taste:
        type: Taste
        list: true

  Brewery:
    table: dbeerpedia.breweries
    sortableBy:
      name:
        - field: name
          direction: ASC
      address:
        - field: postalAddress.street
          direction: ASC
        - field: postalAddress.city
          direction: ASC
      historyAge:
        - field: history.age
          direction: ASC
    filters:
      name: { }
      status: { }
      geometry: { }
      postalStreet:
        field: postalAddress.street
      postalCity:
        field: postalAddress.city
      visitStreet:
        field: visitAddress.street
      visitCity:
        field: visitAddress.city
      historyAge:
        field: history.age
    fields:
      identifier:
        type: ID
      name:
        type: String
      status:
        type: String
      geometry:
        type: Geometry
        nullable: true
      postalAddress:
        type: Address
        nullable: true
        joinColumns:
          - name: postal_address
            referencedField: identifier
      visitAddress:
        type: Address
        nullable: true
        joinColumns:
          - name: visit_address
            referencedField: identifier
      beers:
        type: Beer
        list: true
        nullable: true
        mappedBy: brewery
      beerAgg:
        aggregationOf: Beer
        mappedBy: brewery
      history:
        type: History


  Ingredient:
    table: dbeerpedia.ingredients
    fields:
      identifier:
        type: ID
      name:
        type: String
      weight:
        type: Float

  Address:
    table: dbeerpedia.addresses
    fields:
      identifier:
        type: ID
      street:
        type: String
      city:
        type: String

  History:
    fields:
      age:
        type: Int
        column: his_age
      history:
        type: String
        column: his_history

enumerations:
  Taste:
    values: [MEATY, FRUITY, SMOKY, SPICY, WATERY]
