objectTypes:
  Beer:
    backend: postgres
    table: dbeerpedia.beers
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      abv:
        type: Float
      brewery:
        type: Brewery
        joinColumns:
          - name: brewery
            referencedField: identifier
      ingredients:
        type: Ingredient
        list: true
        joinTable:
          name: dbeerpedia.beers_ingredients
          joinColumns:
            - name: beers_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: ingredients_identifier
              referencedField: identifier
  #      ingredientAgg:
  #        aggregationOf: Ingredient
  #        joinTable:
  #          name: db.beer_ingredient
  #          joinColumns:
  #            - name: beer_identifier
  #              referencedField: identifier_beer
  #          inverseJoinColumns:
  #            - name: ingredient_identifier
  #              referencedField: identifier_ingredient

  Ingredient:
    backend: postgres
    table: dbeerpedia.ingredients
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      weight:
        type: Float

  Brewery:
    backend: postgres
    table: dbeerpedia.breweries
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      status:
        type: String
      postalAddress:
        type: Address
        nullable: true
        joinColumns:
          - name: postal_address
            referencedField: identifier
      visitAddress:
        type: Address
        nullable: true
        joinColumns:
          - name: visit_address
            referencedField: identifier
      beers:
        type: Beer
        mappedBy: brewery
  #      beerAgg:
  #        aggregationOf: Beer
  #        mappedBy: brewery

  Address:
    backend: postgres
    table: dbeerpedia.addresses
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      street:
        type: String
      city:
        type: String
