subscriptions:
  beerSubscription:
    type: Beer
  brewerySubscription:
    type: Brewery

queries:
  beer:
    type: Beer
    keys:
      - field: identifier
  beerCollection:
    type: Beer
    list: true
  brewery:
    type: Brewery
    keys:
      - field: identifier
  breweryCollection:
    type: Brewery
    list: true

objectTypes:
  Beer:
    backend: postgres
    table: dbeerpedia.beers
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      abv:
        type: Float
      soldPerYear:
        type: Float
      brewery:
        type: Brewery
        joinColumns:
          - name: brewery
            referencedField: identifier
      ingredients:
        type: Ingredient
        list: true
        joinTable:
          name: dbeerpedia.beers_ingredients
          joinColumns:
            - name: beers_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: ingredients_identifier
              referencedField: identifier
      ingredientAgg:
        aggregationOf: Ingredient
        joinTable:
          name: dbeerpedia.beers_ingredients
          joinColumns:
            - name: beers_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: ingredients_identifier
              referencedField: identifier
      taste:
        type: Taste
        list: true

  Brewery:
    backend: postgres
    table: dbeerpedia.breweries
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      status:
        type: String
      geometry:
        type: Geometry
        nullable: true
        arguments:
          - name: type
            type: GeometryType
            nullable: true
      postalAddress:
        type: Address
        nullable: true
        joinColumns:
          - name: postal_address
            referencedField: identifier
      visitAddress:
        type: Address
        nullable: true
        joinColumns:
          - name: visit_address
            referencedField: identifier
      beers:
        type: Beer
        list: true
        nullable: true
        mappedBy: brewery
        list: true
        nullable: true
      beerAgg:
        aggregationOf: Beer
        mappedBy: brewery

  Ingredient:
    backend: postgres
    table: dbeerpedia.ingredients
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      name:
        type: String
      weight:
        type: Float

  Address:
    backend: postgres
    table: dbeerpedia.addresses
    keys:
      - field: identifier
    fields:
      identifier:
        type: ID
      street:
        type: String
      city:
        type: String

enumerations:
  Taste:
    values: [MEATY, FRUITY, SMOKY, SPICY, WATERY]

