typeMapping:
  Beer:
    backend: postgres
    table: dbeerpedia.beers
    keys:
      - field: identifier
    fields:
      brewery:
        joinColumns:
          - name: brewery
            referencedField: identifier
      ingredients:
        joinTable:
          name: dbeerpedia.beers_ingredients
          joinColumns:
            - name: beers_identifier
              referencedField: identifier
          inverseJoinColumns:
            - name: ingredients_identifier
              referencedField: identifier
      ingredientAgg:
        aggregationOff: ingredients

  Ingredient:
    backend: postgres
    table: dbeerpedia.ingredients
    keys:
      - field: identifier

  Brewery:
    backend: postgres
    table: dbeerpedia.breweries
    keys:
      - field: identifier
    fields:
      postalAddress:
        joinColumns:
          - name: postal_address
            referencedField: identifier
      visitAddress:
        joinColumns:
          - name: visit_address
            referencedField: identifier
      beers:
        mappedBy: brewery
      beerAgg:
        aggregationOff: beers

  Address:
    backend: postgres
    table: dbeerpedia.addresses
    keys:
      - field: identifier
